site/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', array('uses' => 'AlbumController@index'));

Route::group(array('before' => 'auth.admin'), function () {
    Route::resource('photo', 'PhotoController', array('except' => array('index', 'show')));
    Route::get('photo/create/{album}', 'PhotoController@create')->where('album', '[0-9]+');
    Route::resource('album', 'AlbumController', array('except' => array('index', 'show')));
    Route::resource('user', 'UserController');
});
Route::resource('photo', 'PhotoController', array('only' => array('index', 'show')));
Route::resource('album', 'AlbumController', array('only' => array('index', 'show')));

Route::get('logout', array('as' => 'logout', function () {
    Auth::logout();
    return Redirect::to('/')->with('success', 'Successfully logged out.');
}));
Route::controller('login', 'LoginController');
Route::controller('register', 'RegisterController');

Route::controller('comment', 'CommentController');
Route::controller('like', 'LikeController');

Route::controller('tag', 'TagController');

site/app/views/show/album.blade.php
@extends('master')

@section('panel-heading')
{{ e($data['album']->title) }}
<div class="righted">
    {{-- BEGIN ADD BUTTON --}}
    @if (Auth::check() && Auth::user()->isAdmin())
    <a href="/photo/create/{{ $data['album']->id }}" class="btn btn-sm btn-success"><span
            class="glyphicon glyphicon-plus"></span> Add photos</a>
    <a href="{{ URL::route('album.edit',array('album'=>$data['album']->id)) }}" class="btn btn-sm btn-warning"><span
            class="glyphicon glyphicon-pencil"></span> Edit album</a>
    @endif
    {{-- END ADD BUTTON --}}
</div>
@stop

@section('panel-body')
<div class="well well-sm">
    <p>{{ e($data['album']->long_description) }}</p>

    <p>{{ e($data['album']->place) }}</p>
</div>
<div class="row">
    @if (count($data['photos'])>0)
    @foreach ($data['photos'] as $photo)
    <div class="col-sm-3 top-padding-10">
        <div class="thumbnail">
            <div class="caption animated">
                <p>{{ e($photo->title) }}</p>
                @if (Auth::check() && Auth::user()->isAdmin())
                {{ Form::open(array('route'=>array('photo.edit',$photo->id),'method'=>'GET','class'=>'inlined')) }}
                {{ Form::button('Edit',array('class'=>'btn btn-info btn-xs fueled-white','type'=>'submit')) }}
                {{ Form::close() }}
                {{ Form::open(array('route'=>array('photo.destroy',$photo->id),'method'=>'DELETE','class'=>'inlined')) }}
                {{ Form::button('Delete',array('class'=>'btn btn-danger btn-xs fueled-white','type'=>'submit')) }}
                {{ Form::close() }}
                @endif
                <a href="{{ URL::route('photo.show',array('photo'=>$photo->id)) }}" class="btn btn-success btn-xs fueled-white" rel="tooltip" title="View">View</a>
                @if (Auth::check())
                @if (!in_array($photo->id,$liked))
                <a href="{{ URL::action('LikeController@getStore',$photo->id) }}" class="btn btn-warning btn-xs fueled-white like" rel="tooltip" title="Like">Like ({{ $photo->total_likes }})</a>
                @else
                <a href="{{ URL::action('LikeController@getDestroy',$photo->id) }}" class="btn btn-warning btn-xs fueled-white unlike" rel="tooltip" title="Un-Like">Un-Like ({{ $photo->total_likes }})</a>
                @endif
                @else
                <a href="#" class="btn btn-warning btn-xs fueled-white" rel="tooltip" title="Like">Likes ({{ $photo->total_likes }})</a>
                @endif
            </div>
            <a href="/photo/{{ $photo->id }}">
            <img src="{{ URL::to('/uploads/images/thumbs/'.e($photo->file)) }}"
                 class="photo-thumb-album" alt="{{ e($photo->title) }}">
            </a>
        </div>
    </div>
    @endforeach
    @else
    <div class="col-sm-12"><span class="text-warning">No photos found yet.</span>
    @endif
</div>
@stop

@section('pagination')
{{ $data['photos']->links() }}
@stop

site/app/views/show/photo.blade.php
@extends('master')

@section('panel-heading')
{{ e($photo->title) }}
<div class="righted">
    {{-- BEGIN ADD BUTTON --}}
    @if (Auth::check() && Auth::user()->isAdmin())
    <a href="{{ URL::route('photo.edit',array('photo'=>$photo->id)) }}" class="btn btn-sm btn-warning"><span
            class="glyphicon glyphicon-pencil"></span> Edit photo</a>
    @endif
    {{-- END ADD BUTTON --}}
    @if (Auth::check())
        @if (!in_array($photo->id,$liked))
        <a href="{{ URL::action('LikeController@getStore',$photo->id) }}" class="btn btn-sm btn-info"><span
                class="glyphicon glyphicon-thumbs-up"></span> Like photo ({{ $photo->total_likes }})</a>
        @else
        <a href="{{ URL::action('LikeController@getDestroy',$photo->id) }}" class="btn btn-sm btn-info"><span
                class="glyphicon glyphicon-thumbs-down"></span> Un-Like photo ({{ $photo->total_likes }})</a>

        @endif
    @endif
</div>
@stop

@section('panel-body')
<div class="well well-sm">
    <p>{{ e($photo->description) }}</p>

    <p>Taken on: {{ e($photo->taken) }}</p>

    <p>Tags:
    @foreach ($photo->tags as $tag)
        <a href="/tag/search/{{ e($tag['tag']) }}" title="{{ e($tag['tag']) }}">{{ e($tag['tag']) }}</a>,
    @endforeach
    </p>
</div>
<a class="thumbnail" href="#">
    <img src="{{ URL::to('/uploads/images/'.e($photo->file)) }}" class="image-full-size"
         alt="{{ e($photo->title) }}">
</a>
@stop

@section('comments')
<div class="container">
    <div class="row">
        <div class="panel panel-default widget">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-comment"></span>
                <h3 class="panel-title">
                    Recent Comments</h3>
                <span class="label label-info">
                    {{ $photo->total_comments }}</span>
            </div>
            <div class="panel-body">
                @if ($comments->count()>0)
                <ul class="list-group">
                    @foreach ($comments as $comment)
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-xs-12 col-md-12">
                                <div>
                                    <div class="mic-info">
                                        By: {{ e($comment->user->username) }} on {{ $comment->created_at }}
                                    </div>
                                </div>
                                <div class="comment-text">
                                    {{ e($comment->comment) }}
                                </div>
                                @if ((Auth::check() && Auth::user()->id==$comment->user_id) || Auth::user()->isAdmin())
                                <div class="action">
                                    {{ Form::open(array('action'=>array('CommentController@postDestroy',$comment->id),'method'=>'post','class'=>'inlined')) }}
                                        {{ Form::button('<span class="glyphicon glyphicon-trash"></span> Delete this comment',array('class'=>'btn btn-danger btn-xs fueled-white','type'=>'submit')) }}
                                    {{ Form::close() }}

                                </div>
                                @endif
                            </div>
                        </div>
                    </li>
                    @endforeach
                </ul>
                @else
                <div class="col col-sm-12 top-padding-10">
                    No comments yet. You could be first!
                </div>
                @endif
            </div>
            <div class="col col-sm-12 bottom-padding-10">
                @if (Auth::check())
                {{ Form::open(array('action' => array('CommentController@postStore', $photo->id))) }}

                {{ Form::textarea('comment',null,array('placeholder'=>'Type in your message','class'=>'bottom-margin-10 form-control counted','rows'=>5)) }}
                            <h6 class="pull-right" id="counter">320 characters remaining</h6>
                            <button class="btn btn-info" type="submit">Post New Message</button>
                {{ Form::close() }}
                @else
                <span class="label label-danger">You have to be logged in to comment.</span>
                @endif
            </div>

        </div>
        <div class="centered">{{ $comments->links() }}</div>
    </div>
</div>


@stop